### ISSUE TITLE
Comparison with Orion ?

### ISSUE THREAD

**Issue by markrey** [Aeronbroker/Aeron#7]
Hi,

It's great and well planned software.
I wanted to know the comparison with Orion Context broker. Both are Fiware GE and which would be more active.

Any documents available for the same ?

Thank you

**Comment by Aeronbroker** [comment]
Dear Markrey,

till now there is not a document which compares the two components mainly because, even if they have a similar name, they are conceived for different scopes.

The Orion CB is mainly a general purpose broker of data. It means that different typology of data sources (not only IoT data but also OpenData, Big Data Analytics components etc.) are handled by the Orion CB middleware which exposes a single API (NGSI-9 and NGSI-10) for giving access to such data. The general underlying architectural assumption is that sources (ContextAgents) push their information to the OrionCB, which stores it and makes it available to applications.

The IoT Broker is instead specialized for IoT data and IoT communications. Mainly the IoT Broker is a single point of contact for IoT requests which are transparently dispatched to remote IoT Providers. Furthermore other IoT specific concepts like Associations, IoT domain federation, Entity Composition and Semantic IoT are implemented and offered by the IoT Broker. The IoT Broker is also intended for scenarios where the information is only accessed on demand, i.e. sources only advertise that they can provide certain information (using the NGSI-9 interface of the IoT Discovery). When the IoT Broker receives a query or subscription request via its NGSI-10 interface, it first checks for available sources with the IoT Discovery component via the NGSI-9 interface and then queries/subscribes to the respective sources, aggregating the information and providing them to the requester. Thus sources do not have to publish all their information and can decide on a request-basis what to provide. It is also possible to operate IoT Brokers on multiple levels, i.e. introduce a federation layer. Then instead of querying direct NGSI-10 sources, the federation Broker will access other IoT Brokers (or Orion CBs) – such a setting makes sense if there are multiple independent domains that each manages their own data, e.g. in a smart city, but data should be accessible across these domains. Thus the IoT Broker is a component meant to be used for large IoT deployment. It is conceived to be adopted in more complex IoT architecture (see the II scenario here: https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Internet_of_Things_(IoT)_Services_Enablement_Architecture).

In order to have a clearer idea of how the IoT Broker works I would advise to take a look to the following online course: https://edu.fiware.org/mod/scorm/view.php?id=123.
Instead for more information about the Orion CB I would suggest you to make a tour into the good documentation offered by the Context Broker GEri (Generic Enablers reference implementation).

If you have any further question, feel free to come back to us.

Best

Stefan

-------------------------------------------------------
Stefan Gessler
Project Manager and Data Protection Officer
NEC Europe Ltd.
Kurfuersten Anlage 36
D-69115 Heidelberg
GERMANY

phone +49 6221 4342 114
fax +49 6221 4342 155
email: stefan.gessler@neclab.eu<mailto:stefan.gessler@neclab.eu>

| NEC Europe Ltd | Registered Office: Athene, Odyssey Business Park, West End  Road, London, HA4 6QE, GB | Registered in England 2832014
